# Generated by Django 5.0.2 on 2024-08-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coments',
            new_name='comments',
        ),
    ]
