"""
El archivo settings.py es el archivo de configuración central de una aplicación Django. 
Es donde se definen las variables y opciones que controlan el comportamiento de la aplicación en diferentes aspectos, como:

Configuración de la base de datos:
    Tipo de base de datos (MySQL, PostgreSQL, etc.)
    Nombre de la base de datos
    Usuario y contraseña de la base de datos
    Host y puerto de la base de datos
    
Configuración del servidor web:
    Puerto en el que se ejecuta la aplicación
    Modo de depuración
    Entorno de desarrollo o producción

Configuración de aplicaciones:
    Lista de aplicaciones instaladas en el proyecto
    Clases de configuración específicas de cada aplicación

Configuración de seguridad:
    Clave secreta para la generación de cookies y tokens
    Algoritmos de hash para contraseñas
    Permisos y restricciones de acceso

Configuración de internacionalización:
    Idioma por defecto
    Zona horaria
    Formato de fecha y hora

Configuración de correo electrónico:
    Servidor SMTP
    Usuario y contraseña del servidor SMTP
    Remitente por defecto

Configuración de archivos estáticos:
    Directorio donde se almacenan los archivos estáticos
    URL pública para acceder a los archivos estáticos
"""

"""
Django settings for holamundo project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path # Librería que permite trabajar con rutas de directorios

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent #  Se obtiene la ruta absoluta del directorio raíz del proyecto


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oi-+8xwq+suqfx-47op+8-!yz#t)&fkcwcdho!y$bp0p(n!e97' # Cambiar este valor por uno aleatorio

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Habilita o deshabilita la depuración en modo producción (NO EN PRODUCCIÓN)

ALLOWED_HOSTS = [] #  Define las direcciones IP permitidas (si no está vacío, solo se permitirán estas)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #  administración del sitio
    'django.contrib.auth', #  autenticación y autorización
    'django.contrib.contenttypes', #  tipos de contenido
    'django.contrib.sessions', # gestión de sesiones
    'django.contrib.messages', # mensajes flash
    'django.contrib.staticfiles',  # archivos estáticos
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', #  seguridad http
    'django.contrib.sessions.middleware.SessionMiddleware',  # gestiona la sesion
    'django.middleware.common.CommonMiddleware',    # común a todos los peticiones
    'django.middleware.csrf.CsrfViewMiddleware',    # protección contra ataques csrf
    'django.contrib.auth.middleware.AuthenticationMiddleware',    # autentificación y autorización
    'django.contrib.messages.middleware.MessageMiddleware', # manejo de mensajes flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware', #  protección contra ataques clickjacking
]

ROOT_URLCONF = 'holamundo.urls' # ruta principal para resolver las url

TEMPLATES = [ # plantillas para el renderizado de vistas
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'holamundo.wsgi.application' #  configuración wsgi


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [ #  validación de contraseñas
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us' # idioma por defecto ('es' para español)

TIME_ZONE = 'UTC' #  zona horaria por defecto

USE_I18N = True #  habilita el internacionalización para las fechas

USE_TZ = True #  usa la zona horaria del servidor en lugar de UTC


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/' # dirección donde se encuentran los archivos estáticos

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' #  tipo de llave primaria predeterminada
